CREATE TABLE SONGS
(
    STUDENT_ID          VARCHAR2(10) NOT NULL,
    FAMILY_NAME         VARCHAR2(80),
    GIVEN_NAME          VARCHAR2(40),
    OTHER_NAME          VARCHAR2(40),
    PREFERRED_NAME      VARCHAR2(40),
    TITLE               VARCHAR2(6),
    NAME_EFF_DT         DATE,
    DOB                 DATE,
    GENDER              VARCHAR2(1),
    DECEASED_IND        VARCHAR2(1),
    BIRTH_COUNTRY_CD    VARCHAR2(4),
    HOME_LANG_CD        VARCHAR2(4),
    ABOR_TSI_CD         VARCHAR2(2),
    CONSOL_IND          VARCHAR2(1),
    CONSOL_TO_STU_ID    VARCHAR2(10),
    PREF_DISAB_INFO_IND VARCHAR2(1)
    --SAMS_MOD_DT         DATE         NOT NULL,
    --UPDATE_TS           TIMESTAMP(6) NOT NULL,
    --UPDATE_BY           VARCHAR2(64) NOT NULL,
    -- You can add these in when/if you need them
    --CONSTRAINT SAMS_STUDENT_FK2 FOREIGN KEY (BIRTH_COUNTRY_CD) REFERENCES SAMS_COUNTRY,
    --CONSTRAINT SAMS_STUDENT_FK1 FOREIGN KEY (ABOR_TSI_CD) REFERENCES SAMS_ABOR_TSI,
    --CONSTRAINT SAMS_STUDENT_FK3 FOREIGN KEY (HOME_LANG_CD) REFERENCES SAMS_HOME_LANG
);